name: notes_app
description: "A new Flutter project."
 
publish_to: 'none'  
 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter


 
  
 
   #TODO: FIREBASE
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.0.2
  firebase_core_web: ^2.5.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.5
  http: ^1.2.1
 

  lazy_load_scrollview: ^1.3.0
  flutter_animate: ^4.5.0
  cloudinary_public: ^0.23.1
 

  
  #TODO ICONOS
  cupertino_icons: ^1.0.2  
  font_awesome_flutter: ^10.2.1 
  iconly: ^1.0.1 

  #TODO ANIMACIONES
  lottie: ^3.1.2
 
  animated_text_kit: ^4.2.2
  animate_do: ^3.0.2     

  #TODO ALMACENAMIENTO
  sqflite: ^2.2.6
  shared_preferences: ^2.0.15  

  #TODO COMPONENTES
  auto_size_text_plus: ^3.0.2
  forui: ^0.9.1+1
  flutter_colorpicker: ^1.1.0
  timeago: ^3.6.1
  bounce: ^1.0.2
  path_provider: ^2.0.14
  hive: ^2.2.3
  circular_menu: ^4.0.0
  provider: ^6.0.5
  fluttertoast: ^8.2.10
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  universal_io: ^2.2.2
  toastification: ^2.3.0
  url_launcher: ^6.2.6
  motion: ^1.4.1
  shimmer_animation: ^2.2.2
  animations: ^2.0.11
  flutter_physics: ^0.0.2+1
  percent_indicator: ^4.2.3
  badges: ^3.1.2
  
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
 
  smooth_page_indicator: ^1.2.0+3
  timezone: ^0.9.4
  wolt_modal_sheet: ^0.9.4
  intl: ^0.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0

 
flutter:

 
  uses-material-design: true

 
  assets:

 

   #ANIMACIONES LOTTIE


    
    - assets/lottieAnimations/animacionCheck.json
    - assets/lottieAnimations/animacionDelete.json
    - assets/lottieAnimations/animacionDelete2.json
    - assets/lottieAnimations/animacionCheck2.json
    - assets/lottieAnimations/final.json 
    - assets/lottieAnimations/animacionReload.json 
    - assets/images/recursos/perro1.jpg
    - assets/images/recursos/perro2.jpg
    - assets/images/recursos/perro3.jpg
    - assets/images/recursos/perro4.jpg
   

 
 
    
 

 


    
 

 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
       

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Light.ttf

    - family: Sansita
      fonts:
        - asset: assets/fonts/sansita/Sansita-Bold.ttf
        - asset: assets/fonts/sansita/Sansita-Regular.ttf
        - asset: assets/fonts/sansita/Sansita-Medium.ttf
        - asset: assets/fonts/sansita/Sansita-Light.ttf   
        - asset: assets/fonts/sansita/Sansita-ExtraBold.ttf   


    - family: Monserrat
      fonts:
        - asset: assets/fonts/monserrat/MontserratAlternates-Bold.ttf
        - asset: assets/fonts/monserrat/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/monserrat/MontserratAlternates-Medium.ttf
        - asset: assets/fonts/monserrat/MontserratAlternates-Light.ttf    
        - asset: assets/fonts/monserrat/MontserratAlternates-ExtraBold.ttf


    - family: Climate
      fonts:
        - asset: assets/fonts/climate/ClimateCrisis-Regular.ttf


    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Black.ttf
        - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
        - asset: assets/fonts/inter/Inter_18pt-ExtraBold.ttf
        - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf



    - family: Pacifico
      fonts:
        - asset: assets/fonts/pacifico/Pacifico-Regular.ttf



    - family: BowlbyOne 
      fonts:
        - asset: assets/fonts/BowlbyOne-Regular/BowlbyOne-Regular.ttf
 
